name: Debian Check
on: workflow_call

permissions: write-all

jobs:
  call-debian-check-prefix:
    uses: ./.github/workflows/debian-check-prefix.yml
  call-debian-check-version:
    uses: ./.github/workflows/debian-check-version.yml
  call-debian-check-keys:
    uses: ./.github/workflows/debian-check-keys.yml
  add-reviewers:
    needs: [call-debian-check-prefix, call-debian-check-version, call-debian-check-keys]
    uses: ./.github/workflows/add-reviewer-team.yml
